[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = 'phoebuslint'
authors = [
    {name = 'Jakub Wlodek', email = 'jwlodek@bnl.gov'}
]
description = 'Screen generator for CS-Studio Phoebus displays'
readme = {file = 'README.md', content-type = 'text/markdown'}
license = {file = "LICENSE"}
dynamic = ["version"]
requires-python = '>=3.11'
classifiers=[
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: BSD-3-Clause',
    'Operating System :: OS Independent',
    'Development Status :: 3 - Pre-Alpha',
    'Topic :: Software Development :: Linter'
]
dependencies = [
    "phoebusgen @ git+https://github.com/jwlodek/phoebusgen@v4"
]

[project.scripts]
phoebuslint = "phoebuslint.__main__:main"


[dependency-groups]
dev = [
  "pytest",
  "import-linter",
  "pre-commit",
  "ruff",
  "ty",
]

docs = [
  "sphinx",
  "sphinx_rtd_theme",
  "sphinx_autodoc_typehints",
]

[tool.setuptools_scm]
version_file = "phoebuslint/_version.py"

[tool.pyright]
typeCheckingMode = "standard"
reportMissingImports = false # Ignore missing stubs in imported modules
reportMissingTypeStubs = false

[tool.pytest.ini_options]
# Run pytest with all our checkers, and don't spam us with massive tracebacks on error
addopts = """
    --tb=native -vv
    """
# https://iscinumpy.gitlab.io/post/bound-version-constraints/#watch-for-warnings
filterwarnings = "error"
# Doctest python code in docs, python code in src docstrings, test functions in tests
testpaths = "docs src tests"

[tool.ruff]
src = ["src", "tests"]
line-length = 88
lint.select = [
    "B",   # flake8-bugbear - https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "C4",  # flake8-comprehensions - https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "E",   # pycodestyle errors - https://docs.astral.sh/ruff/rules/#error-e
    "F",   # pyflakes rules - https://docs.astral.sh/ruff/rules/#pyflakes-f
    "W",   # pycodestyle warnings - https://docs.astral.sh/ruff/rules/#warning-w
    "I",   # isort - https://docs.astral.sh/ruff/rules/#isort-i
    "UP",  # pyupgrade - https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "SLF", # self - https://docs.astral.sh/ruff/settings/#lintflake8-self
]
exclude = [
    "src/phoebuslint/_version.py",
]

[tool.ruff.lint.per-file-ignores]
# By default, private member access is allowed in tests
# See https://github.com/DiamondLightSource/python-copier-template/issues/154
# Remove this line to forbid private member access in tests
"tests/**/*" = ["SLF001"]

[tool.importlinter]
root_package = "phoebuslint"

[project.urls]
Homepage = "https://github.com/NSLS2/phoebuslint"
Documentation = "https://NSLS2.github.io/phoebuslint"
Repository = "https://github.com/NSLS2/phoebuslint"
"Bug Tracker" = "https://github.com/NSLS2/phoebuslint/issues"
Changelog = "https://github.com/NSLS2/phoebuslint/blob/master/CHANGELOG.md"
